/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Layout1RouteImport } from './routes/layout-1'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndiqueCodigoRouteImport } from './routes/indique.$codigo'
import { Route as IndicaEGanhaSucessoRouteImport } from './routes/indica-e-ganha.sucesso'

const Layout1Route = Layout1RouteImport.update({
  id: '/layout-1',
  path: '/layout-1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndiqueCodigoRoute = IndiqueCodigoRouteImport.update({
  id: '/indique/$codigo',
  path: '/indique/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicaEGanhaSucessoRoute = IndicaEGanhaSucessoRouteImport.update({
  id: '/indica-e-ganha/sucesso',
  path: '/indica-e-ganha/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/layout-1': typeof Layout1Route
  '/indica-e-ganha/sucesso': typeof IndicaEGanhaSucessoRoute
  '/indique/$codigo': typeof IndiqueCodigoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/layout-1': typeof Layout1Route
  '/indica-e-ganha/sucesso': typeof IndicaEGanhaSucessoRoute
  '/indique/$codigo': typeof IndiqueCodigoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/layout-1': typeof Layout1Route
  '/indica-e-ganha/sucesso': typeof IndicaEGanhaSucessoRoute
  '/indique/$codigo': typeof IndiqueCodigoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/layout-1' | '/indica-e-ganha/sucesso' | '/indique/$codigo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/layout-1' | '/indica-e-ganha/sucesso' | '/indique/$codigo'
  id:
    | '__root__'
    | '/'
    | '/layout-1'
    | '/indica-e-ganha/sucesso'
    | '/indique/$codigo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Layout1Route: typeof Layout1Route
  IndicaEGanhaSucessoRoute: typeof IndicaEGanhaSucessoRoute
  IndiqueCodigoRoute: typeof IndiqueCodigoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/layout-1': {
      id: '/layout-1'
      path: '/layout-1'
      fullPath: '/layout-1'
      preLoaderRoute: typeof Layout1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indique/$codigo': {
      id: '/indique/$codigo'
      path: '/indique/$codigo'
      fullPath: '/indique/$codigo'
      preLoaderRoute: typeof IndiqueCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indica-e-ganha/sucesso': {
      id: '/indica-e-ganha/sucesso'
      path: '/indica-e-ganha/sucesso'
      fullPath: '/indica-e-ganha/sucesso'
      preLoaderRoute: typeof IndicaEGanhaSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Layout1Route: Layout1Route,
  IndicaEGanhaSucessoRoute: IndicaEGanhaSucessoRoute,
  IndiqueCodigoRoute: IndiqueCodigoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
