/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndicaEGanhaIndexRouteImport } from './routes/indica-e-ganha.index'
import { Route as IndiqueCodigoRouteImport } from './routes/indique.$codigo'
import { Route as IndicaEGanhaSucessoRouteImport } from './routes/indica-e-ganha.sucesso'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicaEGanhaIndexRoute = IndicaEGanhaIndexRouteImport.update({
  id: '/indica-e-ganha/',
  path: '/indica-e-ganha/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndiqueCodigoRoute = IndiqueCodigoRouteImport.update({
  id: '/indique/$codigo',
  path: '/indique/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicaEGanhaSucessoRoute = IndicaEGanhaSucessoRouteImport.update({
  id: '/indica-e-ganha/sucesso',
  path: '/indica-e-ganha/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/indica-e-ganha/sucesso': typeof IndicaEGanhaSucessoRoute
  '/indique/$codigo': typeof IndiqueCodigoRoute
  '/indica-e-ganha/': typeof IndicaEGanhaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/indica-e-ganha/sucesso': typeof IndicaEGanhaSucessoRoute
  '/indique/$codigo': typeof IndiqueCodigoRoute
  '/indica-e-ganha': typeof IndicaEGanhaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/indica-e-ganha/sucesso': typeof IndicaEGanhaSucessoRoute
  '/indique/$codigo': typeof IndiqueCodigoRoute
  '/indica-e-ganha/': typeof IndicaEGanhaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/indica-e-ganha/sucesso'
    | '/indique/$codigo'
    | '/indica-e-ganha/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/indica-e-ganha/sucesso' | '/indique/$codigo' | '/indica-e-ganha'
  id:
    | '__root__'
    | '/'
    | '/indica-e-ganha/sucesso'
    | '/indique/$codigo'
    | '/indica-e-ganha/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndicaEGanhaSucessoRoute: typeof IndicaEGanhaSucessoRoute
  IndiqueCodigoRoute: typeof IndiqueCodigoRoute
  IndicaEGanhaIndexRoute: typeof IndicaEGanhaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indica-e-ganha/': {
      id: '/indica-e-ganha/'
      path: '/indica-e-ganha'
      fullPath: '/indica-e-ganha/'
      preLoaderRoute: typeof IndicaEGanhaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indique/$codigo': {
      id: '/indique/$codigo'
      path: '/indique/$codigo'
      fullPath: '/indique/$codigo'
      preLoaderRoute: typeof IndiqueCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indica-e-ganha/sucesso': {
      id: '/indica-e-ganha/sucesso'
      path: '/indica-e-ganha/sucesso'
      fullPath: '/indica-e-ganha/sucesso'
      preLoaderRoute: typeof IndicaEGanhaSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndicaEGanhaSucessoRoute: IndicaEGanhaSucessoRoute,
  IndiqueCodigoRoute: IndiqueCodigoRoute,
  IndicaEGanhaIndexRoute: IndicaEGanhaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
